### PR TITLE
Add self info command for build tools.

### LINKED ISSUE #288: Add build:self:info command
This should show, at a minimum, the current version of the Build Tools plugin.

Optionally, notifying users that there is an update available as well.

### PR DESCRIPTION
**Pull request by rvtraveller**
Resolves #288.

The command currently shows the directory where you have Build Tools installed, the providers that have tokens set up already, and where to find new releases.

```
terminus build:self:info
```

### CODE REVIEW

**Comment by sugaroverflow** [comment]
@rvtraveller the code looks fine to me, but I'm not really sure how I can test this. Can I run an instance of build tools off this branch?

**Comment by rvtraveller** [comment]
@sugaroverflow yup, if you check out this branch you should be able to run it locally!

**Comment by sugaroverflow** [comment]
👋 I checked out the branch - is there anything else that I need to do to run the branch instance of terminus build tools? It's not recognizing the `self:info` command. 

Here's what I did:
```
git fetch origin pull/341/head:self-info-command
git checkout self-info-command
terminus build:self:info
```
Is the some way to call the terminus plugin directly and/or register the command?

**Comment by rvtraveller** [comment]
What happens if you run it with debugging enabled? `terminus build:self:info -vvv`

**Comment by sugaroverflow** [comment]
Command not found? :( Is it working for you?

```
➜  terminus-build-tools-plugin git:(self-info-command) terminus build:self:info -vvv

In Application.php line 574:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "build:self" namespace.

  Did you mean one of these?
      build
      build-env
      build-env:ci
      build-env:delete
      build:ci
      build:comment
      build:comment:add
      build:credentials
      build:env
      build:env:delete
      build:project
      build:repo
      build:secrets
      build:workflow


Exception trace:
  at /Users/fatimakhalid/terminus/vendor/symfony/console/Application.php:574
 Symfony\Component\Console\Application->findNamespace() at /Users/fatimakhalid/terminus/vendor/symfony/console/Application.php:627
 Symfony\Component\Console\Application->find() at /Users/fatimakhalid/terminus/vendor/symfony/console/Application.php:236
 Symfony\Component\Console\Application->doRun() at /Users/fatimakhalid/terminus/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/fatimakhalid/terminus/vendor/consolidation/robo/src/Runner.php:234
 Robo\Runner->run() at /Users/fatimakhalid/terminus/vendor/pantheon-systems/terminus/src/Terminus.php:108
 Pantheon\Terminus\Terminus->run() at /Users/fatimakhalid/terminus/vendor/pantheon-systems/terminus/bin/terminus:49
```

**Comment by rvtraveller** [comment]
Hmm, it works without issue for me? Maybe try a Terminus cache clear? `terminus self:cache-clear`. 

You're sure you don't have 2 versions of the plugin cloned and only 1 of them recognized by terminus?

**Comment by sugaroverflow** [comment]
Weird, doesn't work after cache-clear either. 

I only have the plugin cloned once, but is there a way to check what terminus is recognizing? I don't see a plugin list command 😅

**Comment by rvtraveller** [comment]
@sugaroverflow just pushed up a commit which should resolve that fatal error when tokens aren't set.

**Comment by sugaroverflow** [comment]
Yay 🎉 works now, thank you!

**Comment by sugaroverflow** [comment]
wohoo tests are passing so I'm merging. Thanks so much @rvtraveller  ✋  (high five)

**Pull request merged**
