### PR TITLE
Improved bitbucket support

### PR DESCRIPTION
**Pull request by NickWilde1990**
This seems to work fine however, the automated tests fail for all the branches on my local. So I'm going to have to dig more into figuring that out or have you merge/pull my branch and test on your CI instance?

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I made a new PR so that the tests could run with credentials; however, I don't know that anyone ever set up CircleCI with credentials to create projects on Bitbucket.

**Comment by alexberendei** [comment]
Any news about why the Bitbucket integration tests fail ?

**Comment by NickWilde1990** [comment]
Because this is in progress - I fixed the tests passing in a fork in a different branch and haven't had time to finish yet, now that I can properly test it.

**Comment by greg-1-anderson** [comment]
Continued in #152 - should be merged shortly.

**Pull request closed without merging**
