### PR TITLE
Add support for readme templates

### PR DESCRIPTION
**Pull request by taeo920**
When creating our own custom WordPress template repository we wanted to pre-populate the readme with local development, deployment, and testing instructions. Initially we tried to use the composer `post-create-project-cmd` script hook but the build tools plugin generates a readme with badges as part of the create project command.

This patch looks for a file named README.template.md and, if found, appends its contents to the README.md generated by the build tools plugin. Additionally, it performs a string replacement to insert the site name wherever it finds the %SITE_NAME% placeholder.

I considered adding a description of this feature to the build tools readme but it seems like it would be more appropriate to add it to the readme of the example template repositories. If this is accepted I'd be happy to write that addition.

### CODE REVIEW

**Comment by sugaroverflow** [comment]
This is great!

I'd like to have the change reflected in both the Build tools repo and also, the example-*-repos - @greg-1-anderson if you think this is a good idea, I can go ahead and create a PR.

**Comment by greg-1-anderson** [comment]
And yeah, I would just go ahead and merge here and improve with follow-up PRs.

**Comment by taeo920** [comment]
@greg-1-anderson I'd be happy to draft up the documentation additions once this is merged.
@sugaroverflow Let me know if you need any additional support from me on the PR.

**Comment by sugaroverflow** [comment]
Tests were run on this through #332 so @rvtraveller this should be good to merge and then I can follow up on the example-*-composer repos?

**Comment by rvtraveller** [comment]
Yes, sounds good and I concur @sugaroverflow. 👍

**Comment by rvtraveller** [comment]
Since the repo is set to not allow the PR to merge unless all the tests are passing, you might need to create another PR within this repository just to be able to let the tests turn green.

**Comment by sugaroverflow** [comment]
Gotcha, I'm on it!

**Comment by sugaroverflow** [comment]
Looks like I may have done something wrong @rvtraveller - I created the pull request to run tests on #328 and after they passed, I merged it, but this one isn't updating. 

I wonder if it's because I updated master on both pull requests - should I have done that on only one of them? 

Thank you for your help with this (and getting used to this build tools workflow)!

**Comment by rvtraveller** [comment]
Hmm. That's weird. My process before was to pull the branch from the fork, then push that branch to the pantheon-systems repo. I'm wondering if because you updated each separately it resulted in the merge master commit having a different hash, which resulted in Github not seeing them as equivalent.

**Comment by greg-1-anderson** [comment]
Yeah, if you did a squash & merge, GitHub won't see this branch as merged. You can just close it.

**Comment by sugaroverflow** [comment]
Oops - thank you for figuring that out! :) I'll go ahead and close this since the functionality was merged with #328

**Comment by sugaroverflow** [comment]
thanks everyone! 🌮

**Pull request closed without merging**
