### PR TITLE
Running tests for 324

### PR DESCRIPTION
**Pull request by sugaroverflow**
Running tests for #324 Add support for readme templates

### CODE REVIEW

**Comment by sugaroverflow** [comment]
heyo @rvtraveller, tests for #324 are passing, but needs approval to merge :)

**Comment by sugaroverflow** [comment]
Also question, the last "running tests for X" didn't need a review - was this because I had to update master?

**Comment by rvtraveller** [comment]
> heyo @rvtraveller, tests for #324 are passing, but needs approval to merge :)

Reviewed!



> Also question, the last "running tests for X" didn't need a review - was this because I had to update master?

Yes. Github tries to not force reviews if it is just updating the branch from master (based on my experience).

**Comment by sugaroverflow** [comment]
Gotcha, thank you! :D

**Pull request merged**
