### PR TITLE
Introduce `--use-ssh` to perform initial repo push over SSH

### LINKED ISSUE #276: Allow for ssh instead of https for the initial push to external Git providers during build:project:create
When running `build:project:create` users may prefer to make the initial commit to the Git provider by using SSH instead of `https`. In the case of self-hosted GitLab, this may be a forced requirement.

### PR DESCRIPTION
**Pull request by danielbachhuber**
* If `--use-ssh` is provided, command runs `$this->git_provider->verifySSHConnect()` to verify the process can connect to the provider over SSH.
* Default SSH URLs are: `git@bitbucket.org`, `git@github.com`, and `git@gitlab.com`. A self-hosted GitLab instance is assumed to be `git@selfhosteddomain.com`.
* `$this->git_provider->pushRepository()` has been adapted to simply `git push` for `--use-ssh`, because the Git remote is already being set on the repo.

Fixes #276

### CODE REVIEW

**Comment by ataylorme** [comment]
@danielbachhuber I'm on the fence of whether we need test coverage variants for this. What do you think?

**Comment by danielbachhuber** [comment]
> @danielbachhuber I'm on the fence of whether we need test coverage variants for this. What do you think?

What if we adapted the existing `test_wordpress_*` jobs to use `--ssh`, such that the Drupal jobs didn't and the WordPress jobs did?

**Comment by ataylorme** [comment]
> What if we adapted the existing test_wordpress_* jobs to use --ssh, such that the Drupal jobs didn't and the WordPress jobs did?

That approach sounds great. It would give us coverage for both options over each repository provider.

**Comment by danielbachhuber** [comment]
@ataylorme Looks like the CircleCI SSH key needs updated permissions in order to `--use-ssh`:

```
 20/24 [=======================>----]  83% [notice] Executing git push --progress origin master
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

**Comment by ataylorme** [comment]
```
Executing git push --progress origin master
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.
```

@danielbachhuber it seems the SSH key CircleCI has set up is read-only. I'll have to coordinate with @greg-1-anderson to get that updated.

**Comment by danielbachhuber** [comment]
@ataylorme Should I revert for now, and we can add it back later?

**Comment by ataylorme** [comment]
> Should I revert for now, and we can add it back later?

No, I don't think we should merge the PR without test coverage, so that means fixing the tests

**Comment by danielbachhuber** [comment]
@greg-1-anderson Any luck getting a new SSH key in place?

**Comment by ataylorme** [comment]
@danielbachhuber access to GitLab and BitBucket is blocked right now. I'm trying to get it unblocked but the accounts Greg created were before we implemented Okta SSO and are now locked behind that.

In the meantime, since GitHub tests are passing, I say we:
- Revert the change to use SSH in GitLab and BitBucket tests
- Merge this PR
- Create a follow up issue to implement SSH testing for GitLab and BitBucket

**Comment by danielbachhuber** [comment]
> Create a follow up issue to implement SSH testing for GitLab and BitBucket

Created with #287

**Comment by danielbachhuber** [comment]
@ataylorme I think this is ready for merge whenever you want to give it another review.

**Pull request merged**
