### PR TITLE
Improved bitbucket support

### PR DESCRIPTION
**Pull request by philltran**
Use Bitbucket App Specific password for authentication. 
https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html

### CODE REVIEW

**Comment by philltran** [comment]
@greg-1-anderson Do you know where the cicle command is from in the test below in test-example-repo.sh?

 > # Confirm that Circle was configured for testing, and that the first test passed.
> 
> (
>     set +ex
>     cd "$TARGET_REPO_WORKING_COPY" && circle token "$CIRCLE_TOKEN" && circle watch
> )

I can't find the documentation on the circle watch. It looks like it is looking for a github url scheme and rejecting the bitbucket repo url. 

Thanks.

**Comment by greg-1-anderson** [comment]
Thanks for all of your work here! We have sort of a chicken-and-egg problem. To make forward progress, I recommend:

- Ignore the bitbucket test failures here for now
- Link from this issue to a passing test on a bitbucket project created by this PR (@philltran)
- Merge this PR and make a stable release of the Terminus Build Tools with BitBucket support (Pantheon)
- Make a new docker container with the stable Terminus Build Tools
- Fix the tests for BitBucket support (Pantheon)
- Profit (Everyone)

I think that fixing the problems with the CircleCI tool will involve writing our own tool, since the one we are using (which is not an official CircleCI tool) does not support watching PRs from BitBucket repositories.

**Comment by philltran** [comment]
Sounds good. I will follow the steps you outlined. 

Where should I host the Docker container?

**Comment by philltran** [comment]
Here is a passing Circle CI test for a project build using Bitbucket as the repo

https://circleci.com/bb/philltran/example-site-ptran13

Bitbucket Repo: https://bitbucket.org/philltran/example-site-ptran13

Command used to build project:
`terminus build:project:create --team="Divine Apparitions" "philltran/example-drops-8-composer":"dev-master@dev" example-site-ptran13 --git="bitbucket"`

**Comment by greg-1-anderson** [comment]
Continuing in #152 - will merge once green.

**Comment by greg-1-anderson** [comment]
Merged!

**Comment by philltran** [comment]
Awesome. Thanks!

**Pull request closed without merging**
