### PR TITLE
Refactor repository and CI server configuration into abstract classes

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by grshane** [comment]
How close is this to being done? This would greatly help what I am working on. 

Are there any things that I can contribute to helping get this merged?

**Comment by greg-1-anderson** [comment]
Thanks for offering to pitch in, @grshane! I'm going to see how much I can accomplish today; if I don't finish, there's something else I need to pick up for the next sprint, so this will become a secondary priority. My hope is to get to the point where we can at least start implementing Travis support before then.

If you'd like to work on this today, please read up on [extending Robo tasks](http://robo.li/extending/), if you're not already familiar, and ping me in [#power-users](https://pantheon.io/docs/power-users/), and we'll see if we can get this merged.

**Comment by greg-1-anderson** [comment]
I decided this PR needed https://github.com/consolidation/Robo/pull/580. Almost done there, but now it is clear that I won't be able to merge here until that PR is in a Robo release, and that Robo release is in a Terminus release.

**Comment by greg-1-anderson** [comment]
@grshane if your requirement is to test with Travis or Jenkins, the latest commit is close enough that you could experiment with creating your own version of the CircleCIProvider class.

If you need BitBucket or GitLab, et. al., the code isn't quite ready for new repository providers; more refactoring is still needed for that.

**Comment by greg-1-anderson** [comment]
I got this PR back on the latest stable Terminus release (now that it includes the Robo version we need), so I should be able to merge this PR pretty soon. At merge, it will be ready for PRs that add new CI providers. Enabling repository providers will take a bit more time.

**Comment by greg-1-anderson** [comment]
@grshane merging now -- this is good for additional CI providers (Jenkins, Travis et. al). I will write up some documentation in a bit. Look for more refactoring to support additional repository providers (BitBucket, GitLab et. al) in a future PR.

**Comment by greg-1-anderson** [comment]
This work is continuing in #55

**Pull request merged**
