### PR TITLE
WIP - Trying wordpress as source

### PR DESCRIPTION
**Pull request by stevector**
@greg-1-anderson, I expect this will break, but I'm not exactly sure how. Can you give me write access to this repo so that the PR can build with write access?

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Done -- not sure why there isn't a build for this PR on Circle. Maybe try pushing another commit?

**Comment by greg-1-anderson** [comment]
The main problem this PR will have (assuming that the WordPress example project is working correctly) is that build-env:create project will attempt to call `drush site-install` on the site. See  [my comment about this](https://github.com/pantheon-systems/example-drops-8-composer/pull/60#issuecomment-285950012) in the example-drops-8-composer project.

**Comment by greg-1-anderson** [comment]
With #26, it is now possible to put the command to run to install the CMS in the `['extra']['build-env']['install-cms']` section of composer.json.

**Comment by stevector** [comment]
Over the weekend I got `terminus build-env:create-project stevector/example-wordpress-composer persch-ewc-m --stability=dev --yes` to complete successfully. I need to do some more cleanup and update this PR.

**Comment by stevector** [comment]
replaced by https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/39

**Pull request closed without merging**
