### PR TITLE
Increase workflow timeout and add better logging

### PR DESCRIPTION
**Pull request by greg-1-anderson**
#353 pushed to origin.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
We need a newer version of PHP in the docker container to fix those failures.

**Comment by greg-1-anderson** [comment]
If we merge this, then we can rebase with #346 and fix the problem there.

**Comment by greg-1-anderson** [comment]
We're still having errors like `./.circleci/watch-circle.sh: line 14: circle: command not found` in some tests that are green.

Code has rotted. 😢

**Comment by greg-1-anderson** [comment]
Oh wow tests passing! Thanks @jburianek !

**Comment by greg-1-anderson** [comment]
I can't approve my own PR (GitHub views it as mine), but I am +1 on merging this @sugaroverflow

**Comment by jburianek** [comment]
No problem, figured I might as well fix it while I'm in here 😃

**Comment by jburianek** [comment]
Looks like I can merge this, any idea when we'll cut a new release after that?

Ideally we'd release on every merge to master using something like [autotag](https://github.com/pantheon-systems/autotag).

**Comment by sugaroverflow** [comment]
haha, I got to this too late, thanks @jburianek ! I'll look into using autotag, thanks.

**Comment by greg-1-anderson** [comment]
Release schedule is up to @sugaroverflow. For an example repo such as this, auto-releasing on every merge to the default branch would be fine.

**Pull request merged**
