### PR TITLE
BT-27: Use GIT_SSH_COMMAND for pushing to Pantheon

### PR DESCRIPTION
**Pull request by rvtraveller**
Let's the workflow just run and run and run without getting stuck waiting for the user to accept an SSH host key prompt.

### CODE REVIEW

**Comment by ataylorme** [comment]
We should also consider disabling strict host checking for specific domains, e.g. `*.drush.in`, instead of globally.

**Comment by rvtraveller** [comment]
New day yields new thoughts on how to tackle this and the revelation as to why `putenv()` wasn't working. I like this implementation much more than my previous one.

By using `putenv()`, the environment variable should only be set for the execution of the PHP code and not persisted for the user permanently. This has the advantage of not worrying about overwriting a user's preset `GIT_SSH_COMMAND` (which the prior implementation would do). It applies itself to any Build Tools command as long as it inherits from `BuildToolsBase`.

I think explicitly whitelisting certain domains is going to get tricky, especially with the introduction of the possibility of _any_ domain for GitLab.

**Comment by greg-1-anderson** [comment]
So let's puzzle this through a bit more. We want to disable strict key checking to *.drush.in because those domains change dynamically, and there is no good way for the user to know whether or not they should accept the warning, so they just have to accept everything anyway. If the user is pushing to some custom GitLab domain, though, they have probably pushed to it before, and therefore have probably already accepted it as a valid known host. If they haven't, then they probably want to see the warning to protect against MITM attacks.

So, I think @ataylorme is right here -- we only want to disable checking for `*.drush.in`.

**Comment by rvtraveller** [comment]
Thinking through it more, I agree with your puzzled thinking. I'll tweak.

**Comment by rvtraveller** [comment]
Digging into this more, the command line options you can pass to ssh (and `GIT_SSH_COMMAND`) don't allow for you to specify an explicit host for Strict Host Key Checking. In order to only have this apply to `*.drush.in` hosts we would need to move this from an init hook back into the `pushCodeToPantheon()` function and would need to unset our variable once complete. Before I switch this up, any thoughts from anyone?

**Comment by greg-1-anderson** [comment]
I think I'd rather keep it like this rather than write / remove ssh config files.

**Comment by rvtraveller** [comment]
Also updated our rsync implementation to ignore SSH host keys so users aren't prompted randomly through PR deletes and such.

**Pull request merged**
