### PR TITLE
[CMS-145] [CMS-146] Add template repository option to project create command.

### PR DESCRIPTION
**Pull request by kporras07**
# Private composer repository.

To use a private repository, define the auth string like this:

```
export TERMINUS_BUILD_TOOLS_COMPOSER_AUTH=json_encoded_string
```

or in .terminus/config.yml as described at https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/main/src/Utility/Config.php#L21

Then, in the build:project:create command, pass a composer-repository option like this:

```
terminus build:project:create --template-repository="https://repo.packagist.com/kporras07" kporras07/example-drops-8-test my-project
```

# Git repository (no composer repository)

To use a git repository, use the terminus command like this:

```
terminus build:project:create --template-repository="git@github.com:kporras07/myrepo.git" kporras07/myrepo-template my-project
```

The package name in the composer.json file into the template repo should be "kporras07/myrepo-template". If kporras07/myrepo is a private repo, you should have access to it in your current terminal.

You can also use it as the following shorthand:

```
terminus build:project:create git@github.com:kporras07/example-drops-8-test.git  buildtoolsd807148
```

During the project creation, the repo will be cloned to gather the right package name from the composer.json file.

### CODE REVIEW

**Comment by kporras07** [comment]
This PR replaces #390

**Comment by greg-1-anderson** [comment]
Could you look at the unrelated failures?  I suspect that the GitHub test might be failing because creating a new repository in GitHub now sets the default branch to `main`.   We need the Pantheon dev environment to always be on `master`, but we could in theory have the local repo have a different default branch name. We'd need to make changes in multiple places in the Build Tools repo to allow for differently-named branches (or maybe just special-case main -> master). It's probably easier to just set the GitHub default branch back to `master`.

Looks like the WordPress failure was transient, and passed after I reran it.

**Comment by kporras07** [comment]
@greg-1-anderson the error on D8-Github is now different than before. And this same /follow call worked as expected in other jobs. Is it possible that it's also a transient error? Could you retry the build one more time? Please

**Comment by greg-1-anderson** [comment]
I thought it got "Branch not found" both times. In any event, I'm rerunning the GitHub test. The Bitbucket tests will also run if it passes this time.

**Comment by greg-1-anderson** [comment]
@kporras07  It looks like it's failing the same way every time. You are correct, however; the Drupal 7 + GitHub + Circle is passing, and it's using the same /follow.

Could you try d8 + GitHub + Circle from the command line and see if you can reproduce?

**Comment by kporras07** [comment]
I just tried this in local and it works as expected. Trying debuging the build via ssh

**Comment by kporras07** [comment]
I ran the test using a different name for TERMINUS_SITE and it worked as expected:

```
 [Progress] Beginning CI testing
 22/24 [=========================>--]  91% [notice] Call CircleCI API: https://circleci.com/api/v1.1/project/github/pantheon-ci-bot/build-tools-43621/follow
 23/24 [==========================>-]  95% [notice] Success! Visit your new site at https://github.com/pantheon-ci-bot/build-tools-43621
 24/24 [============================] 100%
```

**Comment by kporras07** [comment]
Weird! I retried one more time and it worked: https://app.circleci.com/pipelines/github/pantheon-systems/terminus-build-tools-plugin/72/workflows/88b38d7b-1d4b-4a4b-9b5c-d0f431b02060

I also tried a dummy commit and it also worked: https://app.circleci.com/pipelines/github/pantheon-systems/terminus-build-tools-plugin/74/workflows/6b90551c-521c-4654-8df9-4f03215612e2

Then, I reverted the dummy commit and it's still running: https://app.circleci.com/pipelines/github/pantheon-systems/terminus-build-tools-plugin/75/workflows/1bdecb2c-d7de-4d1e-b7a5-a7c1ba7e2e4e

**Comment by greg-1-anderson** [comment]
OK that is strange all right. Let's merge it. 😄

**Review by greg-1-anderson — APPROVED** [review]

**Pull request merged**
