### PR TITLE
Add interactions

### PR DESCRIPTION
**Pull request by aaronbauman**
Address issue #290 allowing bitbucket repos to be assigned to a project.

- Add "extra" option to create:project command, to allow additional arbitrary option inputs
- Create AdditionalInteractionsInterface to allow service providers opportunity to collect additional options

### CODE REVIEW

**Comment by ataylorme** [comment]
> nelsonamaya82 approved these changes

@nelsonamaya82 did you test this change to see if it solves #290 for you?

**Comment by nelsonamaya82** [comment]
> @nelsonamaya82 did you test this change to see if it solves #290 for you?

No, sorry @ataylorme. I'm not sure how to test it, could you guide me please and I'll do it immediately. Thanks!

**Comment by ataylorme** [comment]
@nelsonamaya82 to test you will need to clone [the `add_interactions` branch of @aaronbauman's fork](https://github.com/aaronbauman/terminus-build-tools-plugin/tree/add_interactions) locally into your Terminus Build Tools plugin directory and then run `composer install --no-dev` or [download the `.zip` archive of that branch](https://github.com/aaronbauman/terminus-build-tools-plugin/archive/add_interactions.zip) as your Build Tools plugin directory and run `composer install --no-dev`

**Comment by aaronbauman** [comment]
Once you have the branch installed, you run the build:project:create command with `--org` and `--git=bitbucket` flags, and you should be prompted to choose a project (assuming your org has projects).

**Comment by nelsonamaya82** [comment]
Thank you for your help @ataylorme and @aaronbauman. I installed the branch in my Terminus Build Tools plugin directory, run the `composer install --no-dev` and followed Aaron's instructions, however it didn't prompt to choose a project (my org does have projects). It just assigned it to a random (old) project. Based on the code, I think I should use the new flag `--extra='bitbucket-project=TEAM'` to define a project, right?

Quick question: what happens if the project name I define in that flag doesn't exist? Is it created or should I create it previously on my BB org?

**Comment by ataylorme** [comment]
>  I installed the branch in my Terminus Build Tools plugin directory

@nelsonamaya82 I think there was some misunderstanding. The code from Aaron's branch needs to _replace_ your current Build Tools plugin directory, not be included inside of it. So remove the existing Build Tools plugin and re-install with the branch containing this new code. When you are done testing, remove the branch version of the plugin and revert back to the [latest beta release](https://github.com/pantheon-systems/terminus-build-tools-plugin/releases)

**Comment by nelsonamaya82** [comment]
@ataylorme I did that. I replaced completely my current Build Tools plugin directory with the one from Aaron's branch.

**Comment by nelsonamaya82** [comment]
Sorry, I think I cloned the wrong branch. Retrying now.

**Comment by nelsonamaya82** [comment]
@ataylorme and @aaronbauman, now with the right branch installed, it worked fine, it prompted to choose a project. However when it tried to create the repository it threw an error:

`[CompletionWrapper]  Client error: 'PUT https://api.bitbucket.org/2.0/repositories/WeAreNolte/bb-project-test-2' resulted in a '400 Bad Request' response:
{"type": "error", "error": {"fields": {"project": ["Select a valid choice. That choice is not one of the available choic (truncated...)
[CompletionWrapper]  Exit code 400`

Here you can see a [screenshot](https://cl.ly/21b597006bb8).

**Comment by nelsonamaya82** [comment]
I also realized it's listing just a few projects (9 out of 83), and I thought it was something related to permissions but BB Cloud doesn't manage permissions at project level, just at repo level.

**Comment by ataylorme** [comment]
My guess there would be that it is not handling pagination. I’m not at the computer right now but will take a look at the code tomorrow

**Comment by ataylorme** [comment]
According to [the docs for the create repo API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D#post) the `project` `key` parameter must be either the project key or UUID, *not* project name.

```
Note: In order to set the project for the newly created repository, pass in either the project key or the project UUID as part of the request body as shown in the examples below:
$ curl -X POST -H "Content-Type: application/json" -d '{
    "scm": "git",
    "project": {
        "key": "MARS"
    }
}' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
or
$ curl -X POST -H "Content-Type: application/json" -d '{
    "scm": "git",
    "project": {
        "key": "{ba516952-992a-4c2d-acbd-17d502922f96}"
    }
}' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
```

@nelsonamaya82 what happens when you try with the project ID or key instead of name? Note the project UUID needs to be surrounded by curly braces. For example, `--project='{ba516952-992a-4c2d-acbd-17d502922f96}'`

**Comment by aaronbauman** [comment]
Thanks for the feedback, I will take a look at pagination.

Also, should be possible for the plugin to guess the input type -- uuid, project key, project name -- and translate it accordingly.

**Comment by ataylorme** [comment]
Closing in favor of #296

**Pull request closed without merging**
